sudo: required
dist: bionic
language: python
python:
  - "3.7"

# command to install dependencies
install:
  - sudo add-apt-repository ppa:deadsnakes/ppa --yes
  - sudo apt-get --yes --force-yes install python3-venv
  - pip install ansible
  - pip install flake8
  - pip install wheel       # for ansible-test
  - pip install Jinja2      # for ansible-test
  - pip3 install pyyaml     # for ansible-test
  - pip3 install voluptuous # for ansible-test
  - pip install pyyaml      # for compile test with Python2
  - ansible --version

# command to run tests
script:

  # With flake ignore
  #  E402: <module> level import not at top of file (as per Ansible module developement)
  #  W503: line break before binary operator (PEP8 advices to put logical operator ahead)
  - flake8 library/* --max-line-length=160 --ignore=E402,W503

  # checking yaml syntax is not relevant since there are just examples.
  #- ansible-playbook playbook_aix_flrtvc.yml --syntax-check
  #- ansible-playbook playbook_aix_suma_targets_all.yml --syntax-check

  - bash devops/bin/gen_doc.sh
  - bash devops/bin/sanity_test.sh


