sudo: required
dist: bionic
language: python
python:
  - "3.7"
#  - "2.7"

# command to install dependencies
install:
  - pip install ansible
  - pip install flake8
  #- pip install pycodestyle
  - ansible --version


before_script:
  - mkdir -p ~/.ansible/plugins/modules/
  - cp library/*.py ~/.ansible/plugins/modules/

# command to run tests
script:

  # With flake ignore
  #  E402: <module> level import not at top of file (as per Ansible module developement)
  #  W503: line break before binary operator (PEP8 advices to put logical operator ahead)
  - flake8 library/* --max-line-length=160 --ignore=E402,W503

  # pycodestyle (PEP8)
  #- pycodestyle library/* --max-line-length=160 --ignore=E402,W503

  # checking yaml syntax is not relevant since there are just examples.
  #- ansible-playbook playbook_aix_flrtvc.yml --syntax-check
  #- ansible-playbook playbook_aix_suma_targets_all.yml --syntax-check

  - bash devops/bin/gen_doc.sh
