- name: "FLRTVC on AIX playbook"
  hosts: all
  gather_facts: no
  vars:
    apar: sec
    path: /usr/sys/inst.images
    download: yes
  tasks:
    - name: "FLRTVC"
      flrtvc:
        path: "{{ path }}"
        verbose: yes
        apar: "{{ sec }}"
        force: no
        clean: False
        download_only: "{{ download }}"
      register: result
    - debug: var=result
