- name: "FLRTVC on AIX playbook"
  hosts: all
  gather_facts: no
  vars:
    apar: sec
    path: /usr/sys/inst.images
    check: no
    download: yes
    increase: yes
  tasks:
    - name: "FLRTVC"
      flrtvc:
        path: "{{ path }}"
        verbose: yes
        apar: "{{ apar }}"
        force: no
        clean: False
        check_only: "{{ check }}"
        download_only: "{{ download }}"
        increase_fs: "{{ increase }}"
      register: result
    - debug: var=result
